In [5]:
! pip install numpy
! pip install pandas

In [6]:
import numpy as np
import pandas as pd

In [7]:
# Numpy 배열 생성 실습
a1 = np.arange(1, 10, 1)
print(a1)

a2 = np.zeros(5)
print(a2)

a3 =  np.ones(5)
print(a3)

a4 = np.zeros_like(a1)
print(a4)

a5 = np.ones_like(a1)
print(a5)

a6 = np.eye(3)
print(a6)

a7 = np.full((2, 3), 5)
print(a7)

a8 = np.linspace(0, 10, 5, endpoint=True, retstep=True)
print(a8)

a9 = np.empty((3, 2))
print(a9)


[1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[5 5 5]
 [5 5 5]]
(array([ 0. ,  2.5,  5. ,  7.5, 10. ]), 2.5)
[[1.46923442e+195 4.76693711e+180]
 [2.64521819e+185 6.19640467e+223]
 [3.81187276e+180 9.54593534e-307]]


In [8]:
# 초콜릿 평점 분석 실습

data = np.loadtxt('data/chocolate_rating.csv', delimiter=',')

In [9]:
# 모든 초콜릿의 평균 평점
avgRatings = data[:, 3].mean()

# 평점 4점 이상의 우수 초콜릿
good_choco = data[data[:, 3] >= 4,:]

# # 윗 놈의 id(첫번째 열)의 데이터형을 정수(int64)로 변환
# good_id = good_choco[:, 0].astype(np.int64)

# 우수 초콜릿의 카카오 함유량
good_kakaoPer = good_choco[:, 2]

# 카카오 함유량 중복값 제거
unq_kakaoPer, kakaoPer_count= np.unique(good_kakaoPer, return_counts=True)

# 우수 초콜릿 중 가장 빈도 수가 큰 카카오 함유량
max_index = np.argmax(kakaoPer_count)

# 가장 빈도수가 큰 카카오 함유량(%)
print(unq_kakaoPer[max_index] * 100)

70.0


In [14]:
# 영화 어쩌고 ㅋㅋ 실습

data = np.genfromtxt('data/ratings.dat', delimiter='::', dtype=np.int64)

In [19]:
# 처음 5행의 데이터만 확인
print(data[:5, :])
print()

# data의 형태(shape) 확인
print(data.shape)
print()

[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 [        1      3408         4 978300275]
 [        1      2355         5 978824291]]

(1000209, 4)



In [26]:
# 전체 평균 평점 계산
ratingAvg_total = data[:, 2].mean()

# 사용자 아이디 수집
userIds = np.unique(data[:, 0])

# 사용자별 평점 평균
ratingAvg_user = []
for userId in userIds:
    ratingAvg_user.append([userId, data[data[:, 0] == userId, 2].mean()])

In [29]:
# 사용자별 평점 평균 넘파이 배열로 변환
ratingAvg_user_array = np.array(ratingAvg_user)

# 그 놈을 csv 파일로 저장
np.savetxt('data/ratingAvg_user_array.csv', ratingAvg_user_array, delimiter='::', fmt='%.1f')

In [ ]:
# 영화 ID
movieIds = np.unique(data[:, 1])
1

# 영화별 평점 평균 구하기
ratingAvg_movie = []
for movieId in movieIds:
    ratingAvg_movie.append([movieId, data[data[:, 1] == movieId, 2].mean()])

In [32]:
# 영화별 평점 평균 넘파이 배열로 변환
ratingAvg_movie_arr = np.array(ratingAvg_movie)

# 저 긴놈을 저장
np.savetxt('data/moviestar.csv', ratingAvg_movie_arr, delimiter='::', fmt='%.1f')