In [1]:
! pip install numpy
! pip install pandas

In [3]:
import numpy as np
import pandas as pd

In [13]:
# Series 생성(1차원 자료)
list1 = [2, 3 ,4, 1, 5]
s1 = pd.Series(list1, index=['a', 'b', 'c', 'd', 'e'])  # 인덱스를 원하는 대로 바꿀 수도 있음
print(s1)   # 인덱스와 열로 구성되어있음
print(type(s1))
print(s1.dtype)
print(s1.values)
print(s1.index)

a    2
b    3
c    4
d    1
e    5
dtype: int64
<class 'pandas.core.series.Series'>
int64
[2 3 4 1 5]
Index(['a', 'b', 'c', 'd', 'e'], dtype='object')


In [15]:
# Series 생성(1차원 자료) (2)

s2 = pd.Series(list1)
print(s2)
print(type(s2))
print(s2.dtype)
print(s2.values)
print(s2.index)

0    2
1    3
2    4
3    1
4    5
dtype: int64
<class 'pandas.core.series.Series'>
int64
[2 3 4 1 5]
RangeIndex(start=0, stop=5, step=1)


In [18]:
# Series 생성(1차원 자료) (3)

sdata = {'kim': 85, 'lee': 75, 'choi': 65}
s3 = pd.Series(sdata)
print(s3)
print(type(s3))
print(s3.dtype)
print(s3.values)
print(s3.index) # 딕셔너리는 인덱스가 자동으로 키값으로 들어감

kim     85
lee     75
choi    65
dtype: int64
<class 'pandas.core.series.Series'>
int64
[85 75 65]
Index(['kim', 'lee', 'choi'], dtype='object')


In [21]:
# DataFrame 생성

data = {
    'name': ['민준', '현우', '서연', '동현', '지현'],
    'year': [2023, 2024, 2022, 2025,  2024],
    'points': [1.5, 1.7, 3.6, 2.4, 2.9]
    }

df = pd.DataFrame(data)
df

name  year  points
0   민준  2023     1.5
1   현우  2024     1.7
2   서연  2022     3.6
3   동현  2025     2.4
4   지현  2024     2.9

In [31]:
# DataFrame 생성 (2)
names = ['민준', '현우', '서연', '동현', '지현']
years = [2023, 2024, 2022, 2025,  2024]
points = [1.5, 1.7, 3.6, 2.4, 2.9]

data = [names, years, points]   # 2차원 리스트

df1 = pd.DataFrame(data).T
df1.columns = ['names', 'years', 'points']

df1

names years points
0    민준  2023    1.5
1    현우  2024    1.7
2    서연  2022    3.6
3    동현  2025    2.4
4    지현  2024    2.9

In [ ]:
# DataFrame 생성 (3)

arr = np.array(data).T

df2 = pd.DataFrame(
    arr,
    columns=['names', 'years', 'points'],
    index=['one', 'two', 'three', 'four', 'five']
    )

print(df2)
print(df2.index)
print(df2.columns)
print(df2.values)

      names years points
one      민준  2023    1.5
two      현우  2024    1.7
three    서연  2022    3.6
four     동현  2025    2.4
five     지현  2024    2.9
Index(['one', 'two', 'three', 'four', 'five'], dtype='object')
Index(['names', 'years', 'points'], dtype='object')
[['민준' '2023' '1.5']
 ['현우' '2024' '1.7']
 ['서연' '2022' '3.6']
 ['동현' '2025' '2.4']
 ['지현' '2024' '2.9']]


In [36]:
# 데이터프레임의 한 열을 갖고오면 그건 시리즈임 ㅇㅇ

names = df2['names']
years = df2['years']
points = df2['points']

print(names)
print(years)
print(points)

one      민준
two      현우
three    서연
four     동현
five     지현
Name: names, dtype: object
one      2023
two      2024
three    2022
four     2025
five     2024
Name: years, dtype: object
one      1.5
two      1.7
three    3.6
four     2.4
five     2.9
Name: points, dtype: object


In [41]:
# 데이터프레임의 전반적인 정보를 그냥 딸깍 한번으로 보고싶을 때
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, one to five
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   names   5 non-null      object
 1   years   5 non-null      object
 2   points  5 non-null      object
dtypes: object(3)
memory usage: 160.0+ bytes


In [49]:
chocolate_df = pd.read_csv('data/chocolate_rating.csv', header=None)
chocolate_df.columns = ['id', 'year', 'kakao%', 'rating']
chocolate_df.to_csv('data/chololate_df.csv', index=False)    # index=False를 안하면 인덱스까지 저장되어서 열이 하나 더 늘어난다.

In [50]:
character_df = pd.read_excel('data/characters.xlsx')
character_df.to_excel('data/character_df.xlsx', index=False)